# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TinyConverter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Swinject'
  pod 'SwinjectStoryboard', :git => 'https://github.com/Swinject/SwinjectStoryboard.git', :branch => 'master'

  # Pods for TinyConverter

  target 'TinyConverterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
